### PR TITLE
Adds popup window in my work section

### PR DESCRIPTION
**Pull request by GerardoGomezG**
# Popup ( 🕴️☝️)

## Popup window in Desktop Version
image

## Popup window in Mobile Version
image

### CODE REVIEW

**Comment by GerardoGomezG** [comment]
# It's dynamic now @danyhoshi !

## It loads the information given in the script 😃 


### These are the projects loaded:
image

### This is one of the popup windows:
image

**Comment by GerardoGomezG** [comment]
# Each popup window 🪟  with a link 🔗  to each project

**Review by danyhoshi — APPROVED** [review]
# Very nice interaction! I like the use of the dialog tag! 😄

**Review by danyhoshi — APPROVED** [review]
# 👍 Great! 📈

**Pull request merged**
